version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_prod
    environment:
      POSTGRES_DB: prod_db
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: bQW1CVnowyvnehq4
    volumes:
      - prod_pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_prod
    env_file: .env.prod
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend_prod
    ports:
      - "3001:80"

volumes:
  prod_pgdata:
